apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/rpmbuild-pipeline-environment-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: oci-images
    appstudio.openshift.io/component: environment
    pipelines.appstudio.openshift.io/type: build
  name: environment-on-push
  namespace: rpm-build-pipeline-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rpm-build-pipeline-tenant/environment:{{revision}}
  - name: dockerfile
    value: /Containerfile
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/olm-operator-konflux-sample.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/multi-arch-build-pipeline.yaml
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
